# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	if Vagrant.has_plugin?("vagrant-vbguest")
		config.vbguest.auto_update = false
	end

	config.vm.box = "debian/stretch64"
	# do not use the synced folder at this layer. It might fail, but in the next layer it won't
	# config.vm.synced_folder ".", "/vagrant", type: "virtualbox", mount_options: ["dmode=755,fmode=775"]
	config.ssh.insert_key = false

	config.vm.define "basebox" do |node|
		node.vm.hostname = "basebox"
		node.vm.network "public_network"
		node.vm.network "forwarded_port", guest: 22, id: "ssh", host: 10031
		#Option to upgrade kernel during VM 
		#node.vbguest.installer_options = { allow_kernel_upgrade: true }
	end

	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
      	vb.memory = 1*1024
      	vb.cpus = 1
	end
	
	config.vm.provision "shell", path: "./provisioners/apt-install.sh"

end